name: Nightly Build

on:
  schedule:
    # 毎日午前3時（UTC）に実行
    - cron: '0 3 * * *'
  workflow_dispatch: # 手動実行も可能

jobs:
  full-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        # 全てのNode.jsバージョンでテスト
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run security audit
      run: npm audit --audit-level=high

    - name: Build TypeScript
      run: npm run build

    - name: Run full test suite
      env:
        NODE_OPTIONS: '--max-old-space-size=2048'
      run: npm test

    - name: Run performance tests
      env:
        NODE_OPTIONS: '--max-old-space-size=2048'
      run: npm run test:performance

    - name: Run quality check
      run: npm run analyze:src

    - name: Check memory usage
      run: |
        echo "=== Memory Usage Report ==="
        node -e "console.log('Heap:', process.memoryUsage())"